indexer:
  threads: 8
  source-directory: "classpath:files"
  stop-words-location: "classpath:stop-words.txt"
  minimal-token-length: 3
  ignored-delimiters: [" ", ".", ",", '"', "'", "/", "\\", ".", "[", "]", "{", "}", "(", ")", "<", ">",
                       "*", "+", "-", "=", "~", "!", "?", "^", "#", "@", "%", "&", "$", "|", ";", ":"]
